### PR TITLE
Update dataset + handle multiple cities and cantons per zipcode

### PR DESCRIPTION
**Pull request by kira0269**
This is a PR to solve both issues #46 and #33.

I don't know if you want to keep a "no breaking change promise".
I changed some methods signatures in CantonManager for example.

Tell me if you want me to keep "old" methods and put them in deprecated.

### CODE REVIEW

**Comment by stefanzweifel** [comment]
Thanks for this PR @kira0269! 👏

I'm open to make breaking changes. That's what major versions are here for.
I actually tought about working on these problems myself the last few days; just didn't have the time yet.

As far as I can see, the breaking changes are:

- signature changes in `CantonManager`
- removal of `ZipcodeSearch`

That's just something we will have to mention in the release notes and CHANGELOG.

---

On first look, the PR looks good. The only thing missing are documentation/examples in the README. Do you want to add them? Or should I contribute them?

Will take a closer look at this this weekend.

**Comment by kira0269** [comment]
Hi @stefanzweifel 

I'll add examples on monday. :)
But feel free to contribute if you want this weekend

**Review by stefanzweifel — APPROVED** [review]
Thanks again for your PR. I've …

- renamed the method to `getByZipcodeAndCity()` to be more similar to the rest of the API
- updated the CSV import command to use "Ortschaftsname" instead of "Gemeindename". Several cities/villages I know were no longer in the dataset as their name was _swallowed_ by using the "Gemeindename". (For example "Glattpark" and "Glattbrugg" both are valid cities but belong to the same municipality called "Opfikon".)

Going to merge this and release a new major version.

**Comment by stefanzweifel** [comment]
I was a bit hot-headed and 7124f06 broke the test suite. Will ship a fix soon.

**Pull request merged**
